I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ending_isabel.rpy", line 127, in script
    voice IsabeL_352
  File "renpy/common/00voice.rpy", line 534, in execute_voice
    fn = _audio_eval(fn)
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/ending_isabel.rpy", line 127, in <module>
    voice IsabeL_352
NameError: name 'IsabeL_352' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ending_isabel.rpy", line 127, in script
    voice IsabeL_352
  File "renpy/ast.py", line 2009, in execute
    self.call("execute")
  File "renpy/ast.py", line 1997, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/00voice.rpy", line 534, in execute_voice
    fn = _audio_eval(fn)
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/ending_isabel.rpy", line 127, in <module>
    voice IsabeL_352
NameError: name 'IsabeL_352' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
이세계메이드 1.0
Fri Mar 31 11:42:17 2023
